name: 'PolicyTesting'

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  GO_VERSION: '1.15'

jobs:
  policies:
    name: 'Test Az policies'
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 200
    
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_AD_SUBSCRIPTION_ID }}

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Go tests
      run: |
        go get -u github.com/jstemmer/go-junit-report
        go run ./cmd/policyTester/ -config ./test/ -test.v -test.timeout 120m 2>&1 | go-junit-report > report.xml
    - uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: report.xml
