name: 'Release'

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs: 
  create-release:
    name: create release
    runs-on: ubuntu-latest
    outputs: 
      upload-url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: "Build Changelog"
        id: changelog
        uses: mikepenz/release-changelog-builder-action@29da2cc48e1182ad7728ce396f6f51db43d0a9da # v1.8.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: new release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Policy Tester ${{ steps.get_version.outputs.version }}
          tag_name: ${{ github.ref }}
          body: |
            ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

  build:
    name: build tool binaries
    runs-on: ubuntu-latest
    needs: 
      - create-release
    strategy:
      matrix:
        include:
          - {goos: "linux", goarch: "amd64"}
          - {goos: "windows", goarch: "amd64"}
    steps:
      - name: Checkout
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      
      - name: Install Go
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
        with:
          go-version: '1.17'
      
      - name: Build for ${{ matrix.goos }}
        working-directory: cmd/policyTester
        run: |
          export GOARCH=${{ matrix.goarch }}
          export GOOS=${{ matrix.goos }}
          go build -o bin/ .
          zip -r -j bin/policy-tester.${{ needs.create-release.outputs.version }}.${{ matrix.goos }}-${{ matrix.goarch }}.zip bin/
      
      - name: upload ${{ matrix.goos }} artifact
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload-url }}
          asset_path: cmd/policyTester/bin/policy-tester.${{ needs.create-release.outputs.version }}.${{ matrix.goos }}-${{ matrix.goarch }}.zip
          asset_name: policy-tester.${{ needs.create-release.outputs.version }}.${{ matrix.goos }}-${{ matrix.goarch }}.zip
          asset_content_type: application/zip
